### PR TITLE
Harmonize inputs to `survival_*_*()` functions

### LINKED ISSUE #295: Harmonize input for `survival_prob_*()` and `surival_time_*()` functions
The `survival_prob_*()` and `surival_time_*()` functions typically take a model object as fitted by the engine as input. The exceptions are the two functions for glmnet objects (coxnet), which need the parsnip `model_fit` object (for some additional components that are not stored in the engine fit object directly).

These functions preferably all take the same input object. Since we do need the parsnip fit for glmnet, we'd need to change all the other functions.  This would be a breaking change. They are technically exported but developer-facing and tagged with `@keyword internal`. 

I think it makes sense to bite the bullet now and introduce that breaking change: Those functions are not advertised as user-facing, censored is still in its experimental lifecycle stage, we are still "before the big release cascade" for survival analysis, and we might have to live with this rather big inconsistency for rather long.

### PR DESCRIPTION
**Pull request by hfrick**
closes #295 

revdep checks come back clean:
```
ℹ Comparing results
✔ MachineShop 3.7.0                      ── E: 0     | W: 0     | N: 0    
✔ survex 1.2.0                           ── E: 0     | W: 0     | N: 0    
✔ tidyAML 0.0.4                          ── E: 0     | W: 0     | N: 0  
```

### CODE REVIEW

File: R/bag_tree-rpart.R [hunk 1]
```diff
@@ -1,15 +1,21 @@
 #' A wrapper for survival times with `survbagg` models
-#' @param object A model from `ipred::bagging()`.
+#' @param object A parsnip `model_fit` object resulting from `bag_tree()` with `engine = "rpart"`.
```
Comment (simonpcouch) [inline R/bag_tree-rpart.R:2]: I really appreciate this phrasing—if users are confused by the message and look to the docs, this should clear up confusion. That said, do we want [parsnip::bag_tree()] or [`bag_tree()` with `engine = "rpart"`][parsnip::details_bag_tree_rpart] here?

**Review by simonpcouch — APPROVED** [review]
Looking sharp!☃️

File: R/bag_tree-rpart.R (hunk 1 above)
Comment (hfrick) [reply R/bag_tree-rpart.R:2]: That's a good call, thanks! I'll use the second option because the engine really matters here 👍
