### PR TITLE
Fix interpolation of KM values

### LINKED ISSUE #67: Incorrect interpolation of KM values
The steps in the Kaplan-Meier curve are left-inclusive corresponding to a drop in survival probability at an event time and then staying constant until the next event time.

In our interpolation helper function `km_with_cuts()` we currently cut with `right = TRUE` which corresponds to estimating the survival probability as the one of the _next_ event time rather the previous.

``` r
library(censored)
#> Loading required package: parsnip
library(survival)

cox_fit <- coxph(Surv(stop, event) ~ rx + size + number + strata(enum),
                   data = bladder, x = TRUE)

# predict survival prob at time 20
new_data <- bladder[1:3, ]
times <- 20

# from survival_prob_cph()
y <- survival::survfit(cox_fit, newdata = new_data, conf.int = 0.95)

stack_sf <- censored:::stack_survfit(y, nrow(new_data)) %>%
  # simplify to observation 1
  dplyr::filter(.row == 1) %>%
  dplyr::bind_rows(censored:::prob_template, .)
# the two time points around 20
stack_sf %>%
  dplyr::filter(18 <= .time & .time <= 22)
#> # A tibble: 2 x 6
#>   .time .pred_survival .pred_survival_l… .pred_survival_… .pred_hazard_cu…  .row
#>   <dbl>          <dbl>             <dbl>            <dbl>            <dbl> <int>
#> 1    18          0.535             0.418            0.685            0.625     1
#> 2    22          0.519             0.401            0.672            0.655     1

# from interpolate_km_values_ungrouped()
stack_sf <- censored:::km_with_cuts(stack_sf)
stack_sf %>%
  dplyr::filter(18 <= .time & .time <= 22) %>%
  dplyr::select(.time, .pred_survival, .row, .cuts)
#> # A tibble: 2 x 4
#>   .time .pred_survival  .row .cuts  
#>   <dbl>          <dbl> <int> <fct>  
#> 1    18          0.535     1 (17,18]
#> 2    22          0.519     1 (18,22]
# ^^ this should be cut with left-inclusive intervals:
# the estimated survival probability drops at the event time and is then
# constant until the next event,
# meaning that for time 20 the estimate should 0.535.
# however, our join gives 0.519
tibble::tibble(.time = times) %>%
  censored:::km_with_cuts(times = stack_sf$.time) %>%
  dplyr::rename(.tmp = .time) %>%
  dplyr::left_join(stack_sf, by = ".cuts") %>%
  dplyr::select(.time = .tmp, .cuts, .pred_survival)
#> # A tibble: 1 x 3
#>   .time .cuts   .pred_survival
#>   <dbl> <fct>            <dbl>
#> 1    20 (18,22]          0.519


# this also estimates the survival probability as 0.535
pec::predictSurvProb(cox_fit, new_data[1,], times = 20)
#> Warning in .recacheSubclasses(def@className, def, env): undefined subclass
#> "numericVector" of class "Mnumeric"; definition not updated
#>           [,1]
#> [1,] 0.5349973
```

<sup>Created on 2021-06-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

### PR DESCRIPTION
**Pull request by hfrick**
This closes  #67 by working with left-inclusive intervals for the steps of the KM curve. 

``` r
library(censored)
#> Loading required package: parsnip
library(survival)

cox_fit <- coxph(Surv(stop, event) ~ rx + size + number + strata(enum),
                   data = bladder, x = TRUE)

# predict survival prob at time 20 
new_data <- bladder[1:3, ]
times <- 20 

# from survival_prob_cph()
y <- survival::survfit(cox_fit, newdata = new_data, conf.int = 0.95)

stack_sf <- censored:::stack_survfit(y, nrow(new_data)) %>%
  # simplify to observation 1
  dplyr::filter(.row == 1) %>% 
  dplyr::bind_rows(censored:::prob_template, .)

# from interpolate_km_values_ungrouped()
stack_sf <- censored:::km_with_cuts(stack_sf)
# the two time points around 20
stack_sf %>% 
  dplyr::filter(18 <= .time & .time <= 22) %>% 
  dplyr::select(.time, .pred_survival, .row, .cuts)
#> # A tibble: 2 x 4
#>   .time .pred_survival  .row .cuts  
#>   <dbl>          <dbl> <int> <fct>  
#> 1    18          0.535     1 [18,22)
#> 2    22          0.519     1 [22,23)
# ^^ this are now cut with left-inclusive intervals and
# our join gives 0.535.
tibble::tibble(.time = times) %>%
  censored:::km_with_cuts(times = stack_sf$.time) %>%
  dplyr::rename(.tmp = .time) %>%
  dplyr::left_join(stack_sf, by = ".cuts") %>%
  dplyr::select(.time = .tmp, .cuts, .pred_survival)
#> # A tibble: 1 x 3
#>   .time .cuts   .pred_survival
#>   <dbl> <fct>            <dbl>
#> 1    20 [18,22)          0.535
```

<sup>Created on 2021-06-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

### CODE REVIEW

File: tests/testthat/test-proportional_hazards-survival.R [hunk 1]
```diff
@@ -86,10 +86,13 @@ test_that("survival predictions - stratified", {
   f_fit <- fit(cox_spec,
                Surv(stop, event) ~ rx + size + number + strata(enum),
                data = bladder)
+  exp_f_fit <- coxph(Surv(stop, event) ~ rx + size + number + strata(enum),
+                     data = bladder, x = TRUE)
 
   new_data_3 <- bladder[1:3, ]
   f_pred <- predict(f_fit, new_data = new_data_3,
                     type = "survival", time = c(10, 20))
+  exp_f_pred <- pec::predictSurvProb(exp_f_fit, new_data_3, times = c(10, 20))
```
Comment (topepo) [inline tests/testthat/test-proportional_hazards-survival.R:95]: Can yo `dput()` this or save it as an object? I'd like to get rid of this dependency eventually.

**Review by topepo — CHANGES_REQUESTED** [review]
You might consider using [these changes](tidymodels/parsnip@14c6749) to avoid issues when `gert` or `textshaping` are newly on CRAN

**Review by topepo — APPROVED** [review]
